# Generated by Django 2.2.10 on 2025-02-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='影单名称')),
                ('description', models.TextField(verbose_name='影单简介')),
                ('cover_image', models.URLField(blank=True, null=True, verbose_name='封面图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('movies', models.ManyToManyField(related_name='movie_lists', to='movie.Movie')),
            ],
        ),
    ]
