# Generated by Django 2.2.10 on 2025-02-14 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movielist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielist',
            name='movies',
        ),
        migrations.AlterField(
            model_name='movielist',
            name='cover_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='影单封面图片'),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='影单简介'),
        ),
        migrations.CreateModel(
            name='MovieListMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_lists', to='movie.Movie')),
                ('movie_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movie.MovieList')),
            ],
            options={
                'unique_together': {('movie_list', 'movie')},
            },
        ),
    ]
