# Generated by Django 2.2.10 on 2025-02-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20250214_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielist',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='movielist',
            name='image_link',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='movie_cover', verbose_name='封面图片'),
        ),
    ]
