# Generated by Django 2.2.10 on 2025-02-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20250215_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='image_link',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='movie_list', verbose_name='封面图片'),
        ),
    ]
