# Generated by Django 2.2.10 on 2025-02-15 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20250215_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movielist',
            options={'verbose_name': '影单', 'verbose_name_plural': '影单列表'},
        ),
        migrations.AlterModelOptions(
            name='movielistmovies',
            options={'verbose_name': '影单电影', 'verbose_name_plural': '影单电影列表'},
        ),
    ]
