# Generated by Django 2.2.10 on 2025-03-21 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_movielist_list_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTagPreferenceDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_score', models.FloatField(default=0, verbose_name='偏好评分')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Tags', verbose_name='标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户标签偏好度',
                'verbose_name_plural': '用户标签偏好度',
                'unique_together': {('user', 'tag')},
            },
        ),
    ]
